// ..
import './globals.css'

import { Inter } from 'next/font/google'
import NavBar from './components/navBar/navBar'
import Footer from './components/footer/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Omer Y.',
  description: 'Generated by Omer Yahya',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
        {children}
        <Footer/>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
 
      </body>
    </html>
  )
}
